# Generated by Django 5.1.4 on 2024-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('student', 'Student'), ('admin', 'Admin')], max_length=50),
        ),
    ]
