# Generated by Django 5.1.4 on 2024-12-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mentor_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'number')},
        ),
    ]
