# Generated by Django 5.1.4 on 2024-12-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_group_number_alter_group_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givepoint',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_limits', to='main.mentor'),
        ),
        migrations.AlterField(
            model_name='givepoint',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_limits', to='main.student'),
        ),
        migrations.AlterField(
            model_name='givepoint',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_limits', to='main.pointtype'),
        ),
    ]
